name: GitHub Actions Demo
on:
  push:
    branches:
      - dev
env:
  GH_USERNAME: "$${{ github.actor }}"
jobs:
  deploy-dev-build:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Application Version
      id: version
      uses: paulhatch/semantic-version@v4.0.2
      with:
        tag_prefix: ''
        major_pattern: "(MAJOR)"
        minor_pattern: "(MINOR)"
        bump_each_commit: true
        short_tags: false
        format: "${major}.${minor}.${patch}-${increment}"

    - name: write version info to version.txt and commit
      run: |
        sed "s/AUTOMATED_VERSION/${{ steps.version.outputs.version }}/g" setup.py.template > setup.py
  
    - name: switching to python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: run hello world
      run:  |
        python3 src/hello.py
        
