name: GitHub Actions Demo
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Application Version
      id: version
      uses: paulhatch/semantic-version@v4.0.2
      with:
        tag_prefix: ''
        major_pattern: "(MAJOR)"
        minor_pattern: "(MINOR)"
        bump_each_commit: false
        short_tags: false
        format: "${major}.${minor}.${patch}"
    - name: write version info to version.txt and commit
      run: |
        sed -i "s/AUTOMATED_VERSION/${{ steps.version.outputs.version }}" setup.py
        git config user.email "d.nalinikumar@gmail.com"
        git config user.name "Nalini Kumar Danda"
        git commit version.txt -m "version update"
        git push "https://{{ secrets.GH_TOKEN }}@github.com/dnalinikumar/test-semver2.git"
    